name: Deploy
description: Deploys application to the specific environment

inputs:
  port:
    description: Specify a port for a Python application to run
    required: false
    default: "7001"
  environment:
    description: Environment for a Python application, supports dev, staging, preprod, prod
    required: false
    default: dev
  working_dir:
    description: Working directory where to call the code
    required: true

runs:
  using: "composite"
  steps: 
    - name: Print output
      run: echo "Deployment to ${{ inputs.environment }} has started..."
      shell: powershell
      
    - name: Remove old service
      working-directory: ${{ inputs.working_dir }}
      run: |
        pm2 delete greetings-app-${{ inputs.environment }}; 
        exit 0
      shell: powershell

    - name: Start a new service
      working-directory: ${{ inputs.working_dir }}
      # Needs double escape for --port to be able to run in PowerShell
      run : pm2 start --name greetings-app-${{ inputs.environment }} app.py -- -- --port ${{ inputs.port }}
      shell: powershell
