name: Python greetings

on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  install-pip-deps:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3.5.2
      - uses: ./.github/actions/install-pip

  deploy-dev:
    runs-on: self-hosted
    needs: [install-pip-deps]
    steps:
      - uses: actions/checkout@v3.5.2
      - uses: actions/checkout@v3.5.2
        with:
          repository: mtararujs/python-greetings
          path: python-greetings
      - uses: ./.github/actions/deploy
        with:
          port: 7001
          environment: dev
          working_dir: python-greetings

  test-dev:
    runs-on: self-hosted
    needs: [deploy-dev]
    steps:
      - uses: actions/checkout@v3.5.2
        with:
          clean: false
      - uses: actions/checkout@v3.5.2
        with:
          repository: mtararujs/course-js-api-framework
          path: js-api-tests
          clean: false
      - uses: ./.github/actions/test
        with:
          environment: dev
          working_dir: js-api-tests

  # deploy-stg:
  #   runs-on: self-hosted
  #   needs: [test-dev]
  #   steps:
  #     - uses: actions/checkout@v3.5.2
  #     - uses: ./.github/actions/deploy
  #       with:
  #         port: 2020
  #         environment: 'STG'

  # test-stg:
  #   runs-on: self-hosted
  #   needs: [deploy-stg]
  #   steps:
  #     - uses: actions/checkout@v3.5.2
  #     - uses: actions/checkout@v3.5.2
  #       with:
  #         repository: 'mtararujs/course-js-api-framework'
  #         path: 'api-tests'
  #     - uses: ./.github/actions/test
  #       with:
  #         environment: 'STG'

  # deploy-prd:
  #   runs-on: self-hosted
  #   needs: [test-stg]
  #   steps:
  #     - uses: actions/checkout@v3.5.2
  #     - uses: ./.github/actions/deploy
  #       with:
  #         port: 3030
  #         environment: 'PRD'

  # test-prd:
  #   runs-on: self-hosted
  #   needs: [deploy-prd]
  #   steps:
  #     - uses: actions/checkout@v3.5.2
  #     - uses: actions/checkout@v3.5.2
  #       with:
  #         repository: 'mtararujs/course-js-api-framework'
  #         path: 'api-tests'
  #     - uses: ./.github/actions/test
  #       with:
  #         environment: 'PRD'