name: Python greetings

on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  install-pip-deps:
    runs-on: self-hosted
    steps:
      - uses: ./.github/actions/install-pip

  deploy-dev:
    runs-on: self-hosted
    needs: [install-pip-deps]
    steps:
      - uses: ./.github/actions/deploy
        with:
          port: 7001
          environment: dev

  test-dev:
    runs-on: self-hosted
    needs: [deploy-dev]
    steps:
      - uses: ./.github/actions/test
        with:
          environment: dev

  deploy-stg:
    runs-on: self-hosted
    needs: [test-dev]
    steps:
      - uses: ./.github/actions/deploy
        with:
          port: 7002
          environment: staging

  test-stg:
    runs-on: self-hosted
    needs: [deploy-stg]
    steps:
      - uses: ./.github/actions/test
        with:
          environment: staging

  deploy-preprd:
    runs-on: self-hosted
    needs: [test-stg]
    steps:
      - uses: ./.github/actions/deploy
        with:
          port: 7003
          environment: preprod

  test-preprd:
    runs-on: self-hosted
    needs: [deploy-preprd]
    steps:
      - uses: ./.github/actions/test
        with:
          environment: preprod

  deploy-prd:
    runs-on: self-hosted
    needs: [test-preprd]
    steps:
      - uses: ./.github/actions/deploy
        with:
          port: 7004
          environment: prod

  test-prd:
    runs-on: self-hosted
    needs: [deploy-prd]
    steps:
      - uses: ./.github/actions/test
        with:
          environment: prod
